# gspm project.yml <https://gitlab.com/godot-stuff/gs-project-manager/wikis/schema>
name: gs-logger
path: .
version: 3.1.0-dev
default_type: git
godot:
  version: 3.1
  arch: 64
project:
  url: none
  
assets:

pre_install:

post_install:

pre_build:

post_build:
